### ISSUE TITLE
Add ability to identify songs that match the user’s tastes

### ISSUE THREAD

**Issue by DeveloperHobbit** [stringlytyped/cloudnine#2] opened 2020-03-18 17:01 UTC

**Comment by DeveloperHobbit** [comment] 2020-03-18 17:04
18/03/2020 - When trying to run rails server got an error saying "Your yarn packages are out of date" which is a package manager for java script. Had to research how to update it to be able to run the rails server.

**Comment by DeveloperHobbit** [comment] 2020-03-18 17:27
18/03/2020 - Created a branch for the development session on this date. As this was the first piece of development first had to create a view and controller for the base page of our project. The method which will get the users music taste will be inside this controller

**Comment by DeveloperHobbit** [comment] 2020-03-18 17:28
18/03/2020 - As authentication system not in place yet, decided to use own spotify account as a dummy account which we will access to calculate the valence value on this set of set of songs. Once authentication system in place can integrate this into system built using dummy account

**Comment by DeveloperHobbit** [comment] 2020-03-18 17:38
18/03/2020 - Used the following website for help https://medium.com/@raquel.sae.randall/setting-up-a-spotify-api-in-rails-8d60732fe93

Found out we needed to go to the spotify for developers dashboard. Where Sam signed into his account. You need to create a app on the dashboard in order to use the spotify API in the app. When you create a app it gives you a client ID able to identify the app using the spotify API.

Added the three following gems

**Comment by at00976** [comment] 2020-03-20 21:27
20/03/2020 - Finished the tutorial on https://medium.com/@raquel.sae.randall/setting-up-a-spotify-api-in-rails-8d60732fe93 but came across and error with the routes. The specific error was "uninitialized constant Tracks Did you mean? Rack". This error was fixed by editing the routes.rb file. This was fixed by removing an unnecessary namespace.

After fixing the above error another error was thrown up which was "unknown attribute 'artists' for Track." This was fixed by changing artists to artist.

**Comment by at00976** [comment] 2020-03-26 16:08
26/03/2020 - While researching the RSpotify Gem Annabel found the Github for the development of the gem which contains useful for information about the functions that this gem adds. https://github.com/guilhermesad/rspotify

**Comment by at00976** [comment] 2020-03-28 11:59
27-28/03/2020 - When trying to continue development on 27/03/2020 the command 'rails s' stopped working with the error 'exception with response: 400 bad request'. On the 28/03/2020 Annabel found out that the code causing the error was the RSpotify::authenticate line in spotify_setup.rb. Removing this line allows the 'rails s' command to work again however the playlist generation is dependent on this line meaning that it cannot be left out of the code.

**Comment by at00976** [comment] 2020-04-01 13:28
01/04/2020 - The problem with the authentication was solved by refreshing the secret key parameter in the RSpotify::authenticate line.

Added a new method called "new_playlist" this method take the value calculated in av_val and displays the songs that have a valence score that is at least 0.05 higher then the average valence but not more than 0.15 higher. These are dummy values that represent a 5-15% increase in valence value from the average. Once the mood system and weather system has been implemented these values can be changed into parameters that represent how much of an increase we want based on the users mood and the weather.

The increasing complexity of the algorithm lead to a "429 too many requests" error that is most likely caused by the algorithm requesting too much information from the Spotify API in too short a time frame. This error can sometimes be fixed by restarting the server but a full fix needs to be developed before deployment of the application.

**Comment by DeveloperHobbit** [comment] 2020-04-02 11:30
02/04/2020 Considered the idea of using multiple playlists to calculate the average valence score rather than just using a single playlist like we had to work currently. Said this would be an extended feature which we could add once we have the all functionality working for a single playlist

**Comment by DeveloperHobbit** [comment] 2020-04-02 14:28
/02/04/2020 Me and Annabel discussed how at the moment our program generates subsets of songs from the playlist which is used to calculate the average valence value meaning no new songs are generated. When researching saw there is a method from rspotify from the built in recommendations class called generate that is used to generate new songs. We will use this to generate new songs based of the average valence value

**Comment by at00976** [comment] 2020-04-02 16:19
02/04/2020 - To develop the app further I attempted to integrate the recommendation function that the RSpotify API includes so that the generated playlist will contain a mix of songs that were already in the user's playlist and some that weren't. When trying to get the function to work it had the error "URI::InvalidURIError". This error is most likely caused by the parameter not being the right data type.
By using seed_genres instead of seed_tracks I could get the recommendation function to display data however a lot of the information displayed was unnecessary and trying to use ".tracks" as suggested by the documentation for the RSpotify gem led to a "NoMethodError".

**Comment by at00976** [comment] 2020-04-05 15:12
*Note: the development discussed in this comment is counted as a part of Sprint 3*
04/04/2020 - After trying out the 'Recommendations' method and learning how it worked we developed the recommend method that takes a playlist and recommends 20 songs based on a selection of songs in the playlist. We started by creating a loop that took the playlist and created an array of Spotify IDs for the songs in the playlist, the Spotify ID is an unique key used to identify songs. This array of IDs is needed to seed the 'Recommendations' method. 

Originally we were going to use the whole playlist as a seed but we found out the the seed tracks array could only contain a maximum of 5 songs, after discussing the best way to pick 5 songs from the playlist to use in the seed we decided the best method would be to pick a random block of 5 songs from the array and use those songs as the seed. This means when the recommend method is run it will recommend songs based on a different seed even if the same playlist is used.

A small problem that needs to be fixed in the future is the amount of information that is displayed by the 'Recommendations' method. At the moment is displays all the information available when in reality we only need the track information, the problem with this is that although the official documentation for RSpotify says to use '.tracks' to get just the track information this does not work so we will need to find a new way to get the information to display in the way we want it to.

**Comment by stringlytyped** [comment] 2020-04-07 20:23
I've merged in the authentication code from the master branch and reviewed the changes made by @at00976 and @DeveloperHobbit. Some notes:

- @DeveloperHobbit: You seem to misunderstand the circumstances in which CORS would be needed. If you wanted to use JavaScript running on a webpage at example.com to access information provided by a web server running at google.com, Google would need to use CORS to explicitly indicate that cross-origin requests from example.com are to be allowed. Otherwise, the user's web browser would block the communication to enforce the Same-Origin Policy. Since we aren't performing any cross-origin communication, we do not need to use CORS in any fashion.

- We probably do not need to be able to serialize the Tracks model into JSON. However, I will leave the code for that in for now in case it does come in useful.

- Storing the client_secret in plain-text in a config file that is committed to source control is bad practice because of the security implications. You should rotate the client_secret through the Spotify Developer Dashboard to prevent misuse of your Spotify account.

Integrating the playlist generation with the authentication system is still ongoing.

**Comment by stringlytyped** [comment] 2020-04-09 13:25
The recommendations code was originally defined in the `TracksController` but this is not the best place for it. This code should be in a model because models are responsible for handling data and business logic.

As such, I have moved the `recommend` method to the `User` model (and renamed it `recommended_tracks`). I have also rewritten it to recommend tracks based on the user's past listening history. To do this, I have implemented another method called `random_top_tracks`. This method retrieves 5 random songs from the user's top 50 tracks to be used as seeds for the recommendations API.

Similarly, I have moved the method for calculating the average valence of a playlist to the `Playlist` model. The code to populate the playlist with songs is still outstanding.

The user's OAuth tokens are now stored in a `credentials_json` field in the `User` record and are accessible as a hash through the `credentials` method. To use these credentials to authorize a call to the Spotify API, you can now make use of the new `to_rspotify_user` method.

Finally, the relationships between the various models has be re-thought and the migrations rewritten to be cleaner.

**Comment by stringlytyped** [comment] 2020-04-23 21:36
The code to populate playlists has now been added. The User, Playlist, and Track models had to be extended to support this functionality. Refer to code comments for method documentation.

Initially, the playlists were not being generated correctly and the average valence was not near the target. To debug this, a number of information methods (such as valence_distribution) were added to the Playlist model. These methods may be useful for unit tests so they have been left in the code base.

Additionally, a simple playlist view has been added to show the playlist generated for the currently logged in user.

**Closed** 2020-04-23 21:37 UTC
